packages:
  - .

onlyBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs
  - sharp

overrides:
  '@dataconnect/admin-generated': link:src/dataconnect-admin-generated
  '@dataconnect/generated': link:src/dataconnect-generated
